language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-c-compiler
  - sudo apt-get install -y libzmq3-dev 
  - sudo add-apt-repository -y ppa:ori-livneh/e3
  - sudo apt-get update -qq
  - sudo apt-get install -y libczmq-dev
script: make && make testdaemon
