language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-c-compiler libprotoc-dev
  - sudo apt-get install -y libzmq3-dev 
  - wget http://download.zeromq.org/czmq-1.4.1.tar.gz
  - tar -xzvf czmq-1.4.1.tar.gz
  - pushd czmq-1.4.1 && ./configure --prefix=/usr && make && sudo make install
  - popd
script: make && make testdaemon
